main: net.cupofcode.instruments.Instruments
name: Instruments
version: '${version}'
description: Adds various net.cupofcode.instruments to your server
author: CupOfCode
api-version: 1.21
depend: [packetevents] 